services:
  php-apache:
    container_name: "${CONTAINER_NAME_PREFIX}-apache-php"
    build: .
    volumes:
      - ${PATH_TO_LARAVEL_PROJECT}:/var/www/html
      - ./docker/certs:/etc/apache2/ssl
    ports:
      - "80:80"
      - "443:443"

  db:
    container_name: "${CONTAINER_NAME_PREFIX}-mysql"
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    # ports:
    #   - "3306:3306"
volumes:
  db:
